blank_issues_enabled: false
contact_links:
  - name: Questions / clarifications
    url: https://github.com/torisol/thesolframework/discussions
    about: Ask or discuss ideas before opening an RFC or adopter registration
